### ISSUE TITLE
mbx launch failed

### ISSUE THREAD

**Issue by ravening** [shapeblue/mbx#23]
Ran the command
```
mbx launch qa1-415-kenv-437435d9-kvm
```

this failed with following errors

```
 {errorcode : 431, errortext : u'Please provide valid vnet range. vnet range should be a coma seperated list of vlan ranges. example 500-500,600-601 between 0 and 4095'},
```

```
==== Deploy DC Started ====
Exception Occurred: ['Traceback (most recent call last):\n', '  
File "/usr/lib/python2.7/site-packages/marvin/deployDataCenter.py", 
line 484, in updatePhysicalNetwork\n    ret = self.__apiClient.updatePhysicalNetwork(upnet)\n', ' 
 File "/usr/lib/python2.7/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", 
line 1502, in updatePhysicalNetwork\n    
response = self.connection.marvinRequest(command, response_type=response, method=method)\n', '  
File "/usr/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest\n    
raise e\n', "Exception: Job failed: {jobprocstatus : 0, created : u'2021-11-10T14:30:57+0000', completed : u'2021-11-10T14:30:57+0000', cmd : u'org.apache.cloudstack.api.command.admin.network.UpdatePhysicalNetworkCmd', 
userid : u'09f612e8-4231-11ec-a174-525400db5619', jobstatus : 2, jobid : u'15547657-c0ff-4ce2-89a4-69abb245faf0', jobresultcode : 530, jobresulttype : u'object', jobresult : {errorcode : 431, errortext : 
u'Please provide valid vnet range. vnet range should be a coma seperated list of vlan ranges. 
example 500-500,600-601 between 0 and 4095'}, accountid : u'09f5d96f-4231-11ec-a174-525400db5619'}\n"]
```

**Comment by ravening** [comment]
this is the payload

```
2021-11-10 14:30:57,112 - DEBUG - Payload: {'vlan': u'-', 'response': 'json', 'state': 'Enabled', 'command': 'updatePhysicalNetwork', 'id': u'f887cc00-8d6f-49db-bad2-08f651a2e6bb'}
2021-11-10 14:30:57,112 - DEBUG - ========Sending GET Cmd : updatePhysicalNetwork=======
```

**Comment by rhtyd** [comment]
That appears to be a CloudStack issue than mbx issue. @ravening how was the env deployed, can you share your deploy command parameters and if you changed the marvin cfg file before launching?

**Comment by ravening** [comment]
@rhtyd I just followed the commands mentioned in the readme file.. nothing else

First I rant `mbx init` and after that
`mbx deploy 415-kenv mbxt-kvm-centos7 mbxt-kvm-centos7`

Then I got this error

so i changed the content in `marvin.cfg` under `/export/monkeybox/boxes/qa1-415-kenv-437435d9-kvm` for vlan to `500-600` and it worked fine.


Now other issue I am facing is, the setup in running in a vm which doesnt have UI. So how can I access the nested cloudstack setup?
The vm has ip range in 10.* but the setup has 172.*

**Comment by rhtyd** [comment]
Can you share your host details too @ravening, probably the logic that calculated and determines the vlan/ip range has failed. Also the output of: virsh net-list --all

**Comment by ravening** [comment]
@rhtyd 

```
# virsh net-list --all
 Name        State    Autostart   Persistent
----------------------------------------------
 default     active   yes         yes
 monkeynet   active   yes         yes


# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```


Any other details?

**Comment by rhtyd** [comment]
Thanks @ravening, let me get back to you soon.
In the meanwhile, can you share full logs of both mbx deploy, launch cmd outputs as well as the generated marvin cfg file.

Since we're in CCC21 conference, let's grab sometime tomorrow or on Friday to test/debug it, happy to setup separate call next week too.

**Comment by rhtyd** [comment]
Oh wait, maybe I should document this: do you have `bc` installed?

**Comment by rhtyd** [comment]
Yes I think the docs need to be updated about various utilities such as ssh, scp, bc, sed, awk etc that mbx uses.
If bc is installed, pl try deploying again.

**Comment by ravening** [comment]
@rhtyd yes that was the issue. `bc` should be installed before deploying setup.


Have other issues related to setup like template not ready.. probably will create more issues later.
closing this one
