### ISSUE TITLE
How to deploy 4.16 version

### ISSUE THREAD

**Issue by ravening** [shapeblue/mbx#24]
Is there a way to deploy 4.16 version?
Currently it deploys only 4.15

@rhtyd

**Comment by ravening** [comment]
nvm... i had to make some changes to `mbx` and also json file to add suitable packages and after that I was able to deploy

**Comment by rhtyd** [comment]
Okay @ravening send a PR. I had tested it and worked for me, in fact my talk demo deployed 4.16:
```
mbx deploy mbx-demo mbxt-kvm-centos7 mbxt-kvm-centos7 http://192.168.1.100/416rc3/el7/4.16/
```
(you can replace the last parameter with the url of the 4.16 repo)

**Comment by rohityadavcloud** [comment]
Closing on the previous remarks. Looks like you're able to deploy it.
