### ISSUE TITLE
DOCS: Does mbx work in a nested virtualiazion environment?

### ISSUE THREAD

**Issue by synergiator** [shapeblue/mbx#26]
In the manual it's not put clear whether you need a baremetal environment as a mandatory requirement.

Would mbx run with nested virtualization on a guest VM under ESXi (vmware) hypervisor?

**Comment by rohityadavcloud** [comment]
Thanks @synergiator I'll add that. However, it is possible to run nested VMs (mbx hypervisor VMs on Ubuntu VM that runs on ESXi) but not recommended - it may be slow and unstable esp as in the mbx hypervisor VMs it'll run guest VMs.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/shapeblue/mbx/commit/1d354d8f729e837006b325c9780438976e4c20b9
